---
language: node_js
node_js:
  - "4"

addons:
  chrome: stable

sudo: false

cache:
  yarn: true

env:
  - EMBER_TRY_SCENARIO=ember-default
  - EMBER_TRY_SCENARIO=node-tests

matrix:
  fast_finish: true

before_install:
  # NPM >= 3 is needed for ember-cli
  - npm i -g npm@^3

install:
  - yarn install --no-lockfile

script:
  # Usually, it's ok to finish the test scenario without reverting to the
  # addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
